### ISSUE TITLE
not sure what it is about

### ISSUE THREAD

**Issue by davidmann4** [bigkorupto/sources#1]
we talked at the bitcoin meetup about this, you made a schilling crypto coin? how can I get some?

**Comment by geraldb** [comment]
Welcome. Thanks for the interest. It's a work in progress. The easiest way to get free shillings is join the project :-)   Still working out the details but really not much different from bitcoin.  You will have to run a programm (network node) and you will mine / get free shillings (for your work / service).  For pre-mining still trying to work-in git (as blockchain storage), thus, you're more than welcome to add a block (in text) to the shilling blockchain git repo and you will get rewarded (with free shillings) on startup for sure. Happy new year. Prosit 2018!

**Comment by geraldb** [comment]
PS: If you're interested in helping out / joining - let me know and I send you via GitHub an invitation to the shilling / blockchainaustrai org. Again you're more than welcome. The idea is that all members get free shillings (on startup and for mining). It's proof-of-work and proof-of-authentication :-).
PPS: If all works out there's hopefully a (ruby) crypto meetup every other month or so at RIAT in 2018 (best to ask @parasew).

**Comment by davidmann4** [comment]
interesting, will have a look at it pretty soon
